development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: interpres
  pool: 5
  username: dummy
  password: dummy

test:
  adapter: sqlite3
  database: ':memory:'
  timeout: 500
  encoding: unicode
